### ISSUE TITLE
Trezor integration

### ISSUE THREAD

**Issue by krishnaxfx** [racquemis/electrum-mnx#19]
Hi,

I can't use my trezor. When i choose hardware wallet, it shows no hardware wallet was detected. I tested with the electrum bitcoin (ver 3.1.1), it works with no issues

by the way, my trezor is using the latest firmware, 1.6.1
https://blog.trezor.io/trezor-one-firmware-update-1-6-1-eecd0534ab95

Platform: Windows 10

![image](https://user-images.githubusercontent.com/37756652/37870006-7a73b954-2ffe-11e8-80ec-96ac7c88f75b.png)

**Comment by krishnaxfx** [comment]
by the way, my trezor is using the latest firmware, 1.6.1

https://blog.trezor.io/trezor-one-firmware-update-1-6-1-eecd0534ab95

**Comment by racquemis** [comment]
Electrum MNX is now upgraded to 3.2.3 which would have thr latest trezor library in it supporting the new firmware
